// Code generated by "stringer -type=FocusPolicy -linecomment"; DO NOT EDIT.

package katnip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FocusExclusive-0]
	_ = x[FocusNotAllowed-1]
	_ = x[FocusOnDemand-2]
}

const _FocusPolicy_name = "exclusivenot-allowedon-demand"

var _FocusPolicy_index = [...]uint8{0, 9, 20, 29}

func (i FocusPolicy) String() string {
	if i < 0 || i >= FocusPolicy(len(_FocusPolicy_index)-1) {
		return "FocusPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FocusPolicy_name[_FocusPolicy_index[i]:_FocusPolicy_index[i+1]]
}
