// Code generated by "stringer -type=Layer -linecomment"; DO NOT EDIT.

package katnip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LayerBackground-1]
	_ = x[LayerBottom-2]
	_ = x[LayerTop-3]
	_ = x[LayerOverlay-4]
}

const _Layer_name = "backgroundbottomtopoverlay"

var _Layer_index = [...]uint8{0, 10, 16, 19, 26}

func (i Layer) String() string {
	i -= 1
	if i < 0 || i >= Layer(len(_Layer_index)-1) {
		return "Layer(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Layer_name[_Layer_index[i]:_Layer_index[i+1]]
}
