// Code generated by "stringer -type=Layer,FocusPolicy,Edge -linecomment -output panel_string.go"; DO NOT EDIT.

package katnip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LayerBackground-1]
	_ = x[LayerBottom-2]
	_ = x[LayerTop-3]
	_ = x[LayerOverlay-4]
}

const _Layer_name = "backgroundbottomtopoverlay"

var _Layer_index = [...]uint8{0, 10, 16, 19, 26}

func (i Layer) String() string {
	i -= 1
	if i < 0 || i >= Layer(len(_Layer_index)-1) {
		return "Layer(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Layer_name[_Layer_index[i]:_Layer_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FocusExclusive-1]
	_ = x[FocusNotAllowed-2]
	_ = x[FocusOnDemand-3]
}

const _FocusPolicy_name = "exclusivenot-allowedon-demand"

var _FocusPolicy_index = [...]uint8{0, 9, 20, 29}

func (i FocusPolicy) String() string {
	i -= 1
	if i < 0 || i >= FocusPolicy(len(_FocusPolicy_index)-1) {
		return "FocusPolicy(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FocusPolicy_name[_FocusPolicy_index[i]:_FocusPolicy_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EdgeBackground-1]
	_ = x[EdgeBottom-2]
	_ = x[EdgeCenter-3]
	_ = x[EdgeCenterSized-4]
	_ = x[EdgeLeft-5]
	_ = x[EdgeNone-6]
	_ = x[EdgeRight-7]
	_ = x[EdgeTop-8]
}

const _Edge_name = "backgroundbottomcentercenter-sizedleftnonerighttop"

var _Edge_index = [...]uint8{0, 10, 16, 22, 34, 38, 42, 47, 50}

func (i Edge) String() string {
	i -= 1
	if i < 0 || i >= Edge(len(_Edge_index)-1) {
		return "Edge(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Edge_name[_Edge_index[i]:_Edge_index[i+1]]
}
